### ISSUE TITLE
Xargo seems not find my target

### ISSUE THREAD

**Issue by kinggoesgaming** [japaric/xargo#187] opened 2017-12-27 04:44 UTC
I have a custom target for a libc that I am working on https://github.com/cirs/cirs
I have the spec here: https://github.com/cirs/cirs/blob/master/x86_64-unknown-linux-cirs.json at in the root of my project. But this error seems to pop up in Travis. https://travis-ci.org/cirs/cirs/builds/322038812

Mind with any help thanks :)

**Comment by japaric** [comment] 2017-12-27 20:59
duplicate of #186

**Closed by japaric** 2017-12-27 20:59 UTC
